/**
 * Jeu de données de démonstration — hub membre connaissance de soi.
 * Utilisé par `/quiz/hub-membre-capture?filled=1` (et tests E2E).
 * Pas d’INSERT en prod : fixtures purement locales / preview.
 */
import type { MemberProgressMonth } from '@/lib/self-knowledge/progress-monthly';
import type {
  HealthEntryRow,
  JournalEntryRow,
  ReadingResourceRow,
  SelfTestResultRow,
} from '@/lib/self-knowledge/store';

export const HUB_DEMO_TESTS: SelfTestResultRow[] = [
  {
    id: 'demo-bf-t2',
    test_slug: 'big-five',
    locale: 'fr',
    email: null,
    profile_id: null,
    answers: {},
    scores: { O: 34, C: 40, E: 26, A: 41, ES: 36 },
    analysis_teaser: 'Tu avances avec constance — ta curiosité et ta fiabilité se renforcent.',
    analysis_full: null,
    analysis_mode: 'bank',
    consent: true,
    consent_at: '2026-09-10T10:00:00Z',
    first_name: 'Camille',
    source_attribution: null,
    test_version: 'ipip-50-v1',
    created_at: '2026-09-10T10:00:00Z',
  },
  {
    id: 'demo-att-t0',
    test_slug: 'attachement',
    locale: 'fr',
    email: null,
    profile_id: null,
    answers: {},
    scores: { anxiety: 3.2, avoidance: 2.8 },
    analysis_teaser: 'Tu as besoin d’être vue — sans te perdre dans le lien.',
    analysis_full: null,
    analysis_mode: 'bank',
    consent: true,
    consent_at: '2026-08-01T10:00:00Z',
    first_name: 'Camille',
    source_attribution: null,
    test_version: 'ecr-s-v1',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'demo-bf-t1',
    test_slug: 'big-five',
    locale: 'fr',
    email: null,
    profile_id: null,
    answers: {},
    scores: { O: 30, C: 34, E: 24, A: 38, ES: 32 },
    analysis_teaser: 'Ta constance se lit déjà dans ton profil — tu tiens mieux le rythme.',
    analysis_full: null,
    analysis_mode: 'bank',
    consent: true,
    consent_at: '2026-07-12T10:00:00Z',
    first_name: 'Camille',
    source_attribution: null,
    test_version: 'ipip-50-v1',
    created_at: '2026-07-12T10:00:00Z',
  },
  {
    id: 'demo-bf-t0',
    test_slug: 'big-five',
    locale: 'fr',
    email: null,
    profile_id: null,
    answers: {},
    scores: { O: 26, C: 30, E: 22, A: 36, ES: 28 },
    analysis_teaser: 'Tu commençais à te regarder avec plus de douceur.',
    analysis_full: null,
    analysis_mode: 'bank',
    consent: true,
    consent_at: '2026-05-02T10:00:00Z',
    first_name: 'Camille',
    source_attribution: null,
    test_version: 'ipip-50-v1',
    created_at: '2026-05-02T10:00:00Z',
  },
];

export const HUB_DEMO_PROGRESS: MemberProgressMonth[] = [
  {
    year_month: '2026-05',
    sessions: 2,
    lives: 1,
    replay_hours: 0.5,
    goal: 8,
    goal_ratio: 0.25,
    active_weeks: 1,
  },
  {
    year_month: '2026-06',
    sessions: 4,
    lives: 2,
    replay_hours: 1.2,
    goal: 8,
    goal_ratio: 0.5,
    active_weeks: 2,
  },
  {
    year_month: '2026-07',
    sessions: 5,
    lives: 3,
    replay_hours: 1.8,
    goal: 8,
    goal_ratio: 0.625,
    active_weeks: 3,
  },
  {
    year_month: '2026-08',
    sessions: 6,
    lives: 4,
    replay_hours: 2.1,
    goal: 8,
    goal_ratio: 0.75,
    active_weeks: 3,
  },
  {
    year_month: '2026-09',
    sessions: 7,
    lives: 5,
    replay_hours: 2.4,
    goal: 8,
    goal_ratio: 0.875,
    active_weeks: 4,
  },
];

export const HUB_DEMO_HEALTH: HealthEntryRow[] = [
  {
    id: 'demo-h1',
    profile_id: 'demo',
    scores: { regularite: 48, recuperation: 55, energie: 42 },
    source: 'manual',
    created_at: '2026-08-05T08:00:00Z',
    sleep_hours: 6.5,
    resting_hr: 64,
    hrv_ms: null,
    active_minutes: 25,
    regularity_sessions: 2,
    note: null,
  },
  {
    id: 'demo-h2',
    profile_id: 'demo',
    scores: { regularite: 55, recuperation: 60, energie: 50 },
    source: 'manual',
    created_at: '2026-08-19T08:00:00Z',
    sleep_hours: 7,
    resting_hr: 62,
    hrv_ms: null,
    active_minutes: 35,
    regularity_sessions: 3,
    note: null,
  },
  {
    id: 'demo-h3',
    profile_id: 'demo',
    scores: { regularite: 62, recuperation: 66, energie: 58 },
    source: 'manual',
    created_at: '2026-09-02T08:00:00Z',
    sleep_hours: 7.2,
    resting_hr: 60,
    hrv_ms: null,
    active_minutes: 45,
    regularity_sessions: 4,
    note: null,
  },
  {
    id: 'demo-h4',
    profile_id: 'demo',
    scores: { regularite: 70, recuperation: 72, energie: 66 },
    source: 'manual',
    created_at: '2026-09-16T08:00:00Z',
    sleep_hours: 7.5,
    resting_hr: 58,
    hrv_ms: null,
    active_minutes: 55,
    regularity_sessions: 5,
    note: null,
  },
];

export const HUB_DEMO_JOURNAL: JournalEntryRow[] = [
  {
    id: 'demo-j1',
    victory: 'J’ai tenu mon cours du mardi même fatiguée.',
    friction: 'J’ai voulu tout rattraper d’un coup.',
    next_step: 'Une séance, pas trois.',
    created_at: '2026-09-20T18:00:00Z',
  },
  {
    id: 'demo-j2',
    victory: 'J’ai noté mon énergie le soir — et j’ai dormi mieux.',
    friction: 'Le weekend m’a fait sauter le replay.',
    next_step: 'Bloquer 20 min dimanche.',
    created_at: '2026-09-14T19:00:00Z',
  },
  {
    id: 'demo-j3',
    victory: 'J’ai dit « je suis là » à Alejandra en visio.',
    friction: 'La caméra me gêne encore un peu.',
    next_step: 'Garder le cadre, même en petit.',
    created_at: '2026-09-07T18:30:00Z',
  },
];

export const HUB_DEMO_PROMPTS = [
  {
    id: 'demo-p1',
    slug: 'souffle',
    title_fr: 'Où as-tu respiré aujourd’hui ?',
    title_es: '¿Dónde respiraste hoy?',
    body_fr: 'Une phrase suffit.',
    body_es: 'Una frase basta.',
  },
  {
    id: 'demo-p2',
    slug: 'corps',
    title_fr: 'Quel endroit du corps te parle ce soir ?',
    title_es: '¿Qué parte del cuerpo te habla esta noche?',
    body_fr: 'Sans juger — juste nommer.',
    body_es: 'Sin juzgar — solo nombrar.',
  },
];

export const HUB_DEMO_CHALLENGES = [
  {
    id: 'demo-c1',
    slug: 'presence',
    title_fr: 'Arriver 3 minutes avant le live',
    title_es: 'Llegar 3 minutos antes del live',
    body_fr: 'Juste pour t’installer.',
    body_es: 'Solo para instalarte.',
    completed: true,
  },
  {
    id: 'demo-c2',
    slug: 'replay',
    title_fr: 'Un replay cette semaine',
    title_es: 'Un replay esta semana',
    body_fr: 'Quand le live te manque.',
    body_es: 'Cuando te falte el live.',
    completed: true,
  },
  {
    id: 'demo-c3',
    slug: 'journal',
    title_fr: 'Trois lignes dans le journal',
    title_es: 'Tres líneas en el diario',
    body_fr: 'Victoire, accroc, prochain pas.',
    body_es: 'Victoria, tropiezo, próximo paso.',
    completed: false,
  },
];

export const HUB_DEMO_RESOURCES: ReadingResourceRow[] = [
  {
    id: 'a0e86d67-ea6b-4c36-81c9-86e4f7f37214',
    title: 'Le corps n’oublie rien',
    author: 'Bessel van der Kolk',
    theme: 'corps',
    why_text: 'Pour comprendre le lien émotions / sensations, sans jargon.',
    locale: 'fr',
    sort_order: 1,
    affiliate_url: 'https://www.awin1.com/cread.php?awinmid=12665&awinaffid=3103771&ued=example',
    disclosure: true,
    resource_type: 'book',
    cover_image_url: '/library/book-covers/a0e86d67-ea6b-4c36-81c9-86e4f7f37214.jpg',
  },
  {
    id: '5389a57b-a514-497c-8530-35e3b908886e',
    title: 'Un rien peut tout changer',
    author: 'James Clear',
    theme: 'habitudes',
    why_text: 'Des micro-gestes qui tiennent dans le temps.',
    locale: 'fr',
    sort_order: 2,
    affiliate_url: 'https://www.awin1.com/cread.php?awinmid=12665&awinaffid=3103771&ued=example2',
    disclosure: true,
    resource_type: 'book',
    cover_image_url: '/library/book-covers/5389a57b-a514-497c-8530-35e3b908886e.jpg',
  },
  {
    id: '66dc7acd-0a28-4981-8eba-b8c7f0542146',
    title: 'Pourquoi j’ai mangé mon père',
    author: 'Roy Lewis',
    theme: 'récit',
    why_text: 'Un regard décalé sur l’évolution — léger et intelligent.',
    locale: 'fr',
    sort_order: 3,
    affiliate_url: 'https://www.awin1.com/cread.php?awinmid=12665&awinaffid=3103771&ued=example3',
    disclosure: false,
    resource_type: 'book',
    cover_image_url: '/library/book-covers/66dc7acd-0a28-4981-8eba-b8c7f0542146.jpg',
  },
  {
    id: '778affab-75f1-4e77-b295-bf2bcc32ece0',
    title: 'Tapis de sol Pilates',
    author: 'Decathlon',
    theme: 'matériel',
    why_text: 'Un sol stable pour pratiquer à la maison.',
    locale: 'fr',
    sort_order: 10,
    affiliate_url: 'https://www.awin1.com/cread.php?awinmid=12665&awinaffid=3103771&ued=gear',
    disclosure: false,
    resource_type: 'gear',
    cover_image_url: null,
  },
  {
    id: '311e03ff-ceef-4f99-b46d-f19359170588',
    title: 'Ballon de gym / Pilates',
    author: 'Decathlon',
    theme: 'matériel',
    why_text: 'Pour le travail de stabilité et de mobilité.',
    locale: 'fr',
    sort_order: 11,
    affiliate_url: 'https://www.awin1.com/cread.php?awinmid=12665&awinaffid=3103771&ued=gear2',
    disclosure: false,
    resource_type: 'gear',
    cover_image_url: null,
  },
];

export const HUB_DEMO_STREAK = 5;
export const HUB_DEMO_FOLLOWED = 7;
export const HUB_DEMO_GOAL = 8;
