import type { SelfTestDefinition, SelfTestItem } from './types';

/**
 * IPIP-NEO-120 (Johnson, 2014) — 30 facettes × 4 items = 120.
 * Source items EN : https://ipip.ori.org/30FacetNEO-PI-RItems.htm
 * Johnson, J. A. (2014). J. Research in Personality, 51, 78–89.
 * FR/ES : traductions fidèles (non validées psychométriquement).
 */

export const IPIP120_FACET_IDS = [
  'N1',
  'N2',
  'N3',
  'N4',
  'N5',
  'N6',
  'E1',
  'E2',
  'E3',
  'E4',
  'E5',
  'E6',
  'O1',
  'O2',
  'O3',
  'O4',
  'O5',
  'O6',
  'A1',
  'A2',
  'A3',
  'A4',
  'A5',
  'A6',
  'C1',
  'C2',
  'C3',
  'C4',
  'C5',
  'C6',
] as const;
export type IpIp120FacetId = (typeof IPIP120_FACET_IDS)[number];

export const IPIP120_ITEMS: SelfTestItem[] = [
  { id: 'N1_p1', key: 'N1', en: "Worry about things.", text: { fr: "Je m\u2019inqui\u00e8te pour les choses.", es: "Me preocupo por las cosas." }, reverse: false },
  { id: 'N1_p2', key: 'N1', en: "Fear for the worst.", text: { fr: "Je crains le pire.", es: "Temo lo peor." }, reverse: false },
  { id: 'N1_p3', key: 'N1', en: "Am afraid of many things.", text: { fr: "J\u2019ai peur de beaucoup de choses.", es: "Tengo miedo de muchas cosas." }, reverse: false },
  { id: 'N1_p4', key: 'N1', en: "Get stressed out easily.", text: { fr: "Je me stresse facilement.", es: "Me estreso con facilidad." }, reverse: false },
  { id: 'N2_p5', key: 'N2', en: "Get angry easily.", text: { fr: "Je me mets en col\u00e8re facilement.", es: "Me enfado con facilidad." }, reverse: false },
  { id: 'N2_p6', key: 'N2', en: "Get irritated easily.", text: { fr: "Je m\u2019irrite facilement.", es: "Me irrito con facilidad." }, reverse: false },
  { id: 'N2_p7', key: 'N2', en: "Lose my temper.", text: { fr: "Je perds mon sang-froid.", es: "Pierdo los estribos." }, reverse: false },
  { id: 'N2_r8', key: 'N2', en: "Am not easily annoyed.", text: { fr: "Je ne m\u2019\u00e9nerve pas facilement.", es: "No me molesto con facilidad." }, reverse: true },
  { id: 'N3_p9', key: 'N3', en: "Often feel blue.", text: { fr: "Je me sens souvent d\u00e9prim\u00e9e.", es: "A menudo me siento triste." }, reverse: false },
  { id: 'N3_p10', key: 'N3', en: "Dislike myself.", text: { fr: "Je ne m\u2019aime pas.", es: "No me gusto a m\u00ed misma." }, reverse: false },
  { id: 'N3_p11', key: 'N3', en: "Am often down in the dumps.", text: { fr: "Je suis souvent au fond du trou.", es: "A menudo estoy deprimida." }, reverse: false },
  { id: 'N3_r12', key: 'N3', en: "Feel comfortable with myself.", text: { fr: "Je me sens \u00e0 l\u2019aise avec moi-m\u00eame.", es: "Me siento a gusto conmigo misma." }, reverse: true },
  { id: 'N4_p13', key: 'N4', en: "Find it difficult to approach others.", text: { fr: "J\u2019ai du mal \u00e0 aborder les autres.", es: "Me cuesta acercarme a los dem\u00e1s." }, reverse: false },
  { id: 'N4_p14', key: 'N4', en: "Am afraid to draw attention to myself.", text: { fr: "J\u2019ai peur d\u2019attirer l\u2019attention sur moi.", es: "Temo llamar la atenci\u00f3n sobre m\u00ed." }, reverse: false },
  { id: 'N4_p15', key: 'N4', en: "Only feel comfortable with friends.", text: { fr: "Je ne me sens \u00e0 l\u2019aise qu\u2019avec des ami\u00b7es.", es: "Solo me siento c\u00f3moda con amigas." }, reverse: false },
  { id: 'N4_r16', key: 'N4', en: "Am not bothered by difficult social situations.", text: { fr: "Les situations sociales difficiles ne me g\u00eanent pas.", es: "Las situaciones sociales dif\u00edciles no me molestan." }, reverse: true },
  { id: 'N5_p17', key: 'N5', en: "Go on binges.", text: { fr: "Je fais des exc\u00e8s.", es: "Me doy atracones." }, reverse: false },
  { id: 'N5_r18', key: 'N5', en: "Rarely overindulge.", text: { fr: "Je c\u00e8de rarement \u00e0 l\u2019exc\u00e8s.", es: "Rara vez me excedo." }, reverse: true },
  { id: 'N5_r19', key: 'N5', en: "Easily resist temptations.", text: { fr: "Je r\u00e9siste facilement aux tentations.", es: "Resisto f\u00e1cilmente las tentaciones." }, reverse: true },
  { id: 'N5_r20', key: 'N5', en: "Am able to control my cravings.", text: { fr: "Je sais contr\u00f4ler mes envies.", es: "Puedo controlar mis antojos." }, reverse: true },
  { id: 'N6_p21', key: 'N6', en: "Panic easily.", text: { fr: "Je panique facilement.", es: "Me pongo en p\u00e1nico con facilidad." }, reverse: false },
  { id: 'N6_p22', key: 'N6', en: "Become overwhelmed by events.", text: { fr: "Les \u00e9v\u00e9nements m\u2019accablent facilement.", es: "Los acontecimientos me abruman." }, reverse: false },
  { id: 'N6_p23', key: 'N6', en: "Feel that I'm unable to deal with things.", text: { fr: "J\u2019ai l\u2019impression de ne pas pouvoir faire face.", es: "Siento que no puedo con las cosas." }, reverse: false },
  { id: 'N6_r24', key: 'N6', en: "Remain calm under pressure.", text: { fr: "Je reste calme sous pression.", es: "Me mantengo calmada bajo presi\u00f3n." }, reverse: true },
  { id: 'E1_p25', key: 'E1', en: "Make friends easily.", text: { fr: "Je me fais facilement des ami\u00b7es.", es: "Hago amigos con facilidad." }, reverse: false },
  { id: 'E1_p26', key: 'E1', en: "Feel comfortable around people.", text: { fr: "Je me sens \u00e0 l\u2019aise avec les gens.", es: "Me siento c\u00f3moda con la gente." }, reverse: false },
  { id: 'E1_r27', key: 'E1', en: "Avoid contacts with others.", text: { fr: "J\u2019\u00e9vite le contact avec les autres.", es: "Evito el contacto con los dem\u00e1s." }, reverse: true },
  { id: 'E1_r28', key: 'E1', en: "Keep others at a distance.", text: { fr: "Je tiens les autres \u00e0 distance.", es: "Mantengo a los dem\u00e1s a distancia." }, reverse: true },
  { id: 'E2_p29', key: 'E2', en: "Love large parties.", text: { fr: "J\u2019adore les grandes f\u00eates.", es: "Me encantan las fiestas grandes." }, reverse: false },
  { id: 'E2_p30', key: 'E2', en: "Talk to a lot of different people at parties.", text: { fr: "Dans les soir\u00e9es, je parle \u00e0 beaucoup de gens diff\u00e9rents.", es: "En las fiestas hablo con mucha gente distinta." }, reverse: false },
  { id: 'E2_r31', key: 'E2', en: "Prefer to be alone.", text: { fr: "Je pr\u00e9f\u00e8re \u00eatre seule.", es: "Prefiero estar sola." }, reverse: true },
  { id: 'E2_r32', key: 'E2', en: "Avoid crowds.", text: { fr: "J\u2019\u00e9vite la foule.", es: "Evito las multitudes." }, reverse: true },
  { id: 'E3_p33', key: 'E3', en: "Take charge.", text: { fr: "Je prends les choses en main.", es: "Tomo el mando." }, reverse: false },
  { id: 'E3_p34', key: 'E3', en: "Try to lead others.", text: { fr: "J\u2019essaie de mener les autres.", es: "Intento liderar a los dem\u00e1s." }, reverse: false },
  { id: 'E3_p35', key: 'E3', en: "Take control of things.", text: { fr: "Je prends le contr\u00f4le.", es: "Tomo el control de las cosas." }, reverse: false },
  { id: 'E3_r36', key: 'E3', en: "Wait for others to lead the way.", text: { fr: "J\u2019attends que les autres montrent le chemin.", es: "Espero a que otros marquen el camino." }, reverse: true },
  { id: 'E4_p37', key: 'E4', en: "Am always busy.", text: { fr: "Je suis toujours occup\u00e9e.", es: "Siempre estoy ocupada." }, reverse: false },
  { id: 'E4_p38', key: 'E4', en: "Am always on the go.", text: { fr: "Je suis toujours en mouvement.", es: "Siempre estoy en marcha." }, reverse: false },
  { id: 'E4_p39', key: 'E4', en: "Do a lot in my spare time.", text: { fr: "Je fais beaucoup de choses pendant mon temps libre.", es: "Hago muchas cosas en mi tiempo libre." }, reverse: false },
  { id: 'E4_r40', key: 'E4', en: "Like to take it easy.", text: { fr: "J\u2019aime prendre les choses tranquillement.", es: "Me gusta tom\u00e1rmelo con calma." }, reverse: true },
  { id: 'E5_p41', key: 'E5', en: "Love excitement.", text: { fr: "J\u2019adore l\u2019excitation.", es: "Me encanta la emoci\u00f3n." }, reverse: false },
  { id: 'E5_p42', key: 'E5', en: "Seek adventure.", text: { fr: "Je cherche l\u2019aventure.", es: "Busco la aventura." }, reverse: false },
  { id: 'E5_p43', key: 'E5', en: "Enjoy being reckless.", text: { fr: "J\u2019aime \u00eatre t\u00e9m\u00e9raire.", es: "Disfruto siendo temeraria." }, reverse: false },
  { id: 'E5_p44', key: 'E5', en: "Act wild and crazy.", text: { fr: "J\u2019agis de fa\u00e7on folle et d\u00e9jant\u00e9e.", es: "Act\u00fao de forma loca y alocada." }, reverse: false },
  { id: 'E6_p45', key: 'E6', en: "Radiate joy.", text: { fr: "Je rayonne de joie.", es: "Irradio alegr\u00eda." }, reverse: false },
  { id: 'E6_p46', key: 'E6', en: "Have a lot of fun.", text: { fr: "Je m\u2019amuse beaucoup.", es: "Me divierto mucho." }, reverse: false },
  { id: 'E6_p47', key: 'E6', en: "Love life.", text: { fr: "J\u2019aime la vie.", es: "Amo la vida." }, reverse: false },
  { id: 'E6_p48', key: 'E6', en: "Look at the bright side of life.", text: { fr: "Je vois le bon c\u00f4t\u00e9 des choses.", es: "Miro el lado bueno de la vida." }, reverse: false },
  { id: 'O1_p49', key: 'O1', en: "Have a vivid imagination.", text: { fr: "J\u2019ai une imagination vive.", es: "Tengo una imaginaci\u00f3n viva." }, reverse: false },
  { id: 'O1_p50', key: 'O1', en: "Enjoy wild flights of fantasy.", text: { fr: "J\u2019aime les envol\u00e9es d\u2019imagination.", es: "Disfruto de vuelos locos de fantas\u00eda." }, reverse: false },
  { id: 'O1_p51', key: 'O1', en: "Love to daydream.", text: { fr: "J\u2019adore r\u00eavasser.", es: "Me encanta so\u00f1ar despierta." }, reverse: false },
  { id: 'O1_p52', key: 'O1', en: "Like to get lost in thought.", text: { fr: "J\u2019aime me perdre dans mes pens\u00e9es.", es: "Me gusta perderme en mis pensamientos." }, reverse: false },
  { id: 'O2_p53', key: 'O2', en: "Believe in the importance of art.", text: { fr: "Je crois \u00e0 l\u2019importance de l\u2019art.", es: "Creo en la importancia del arte." }, reverse: false },
  { id: 'O2_p54', key: 'O2', en: "See beauty in things that others might not notice.", text: { fr: "Je vois la beaut\u00e9 l\u00e0 o\u00f9 d\u2019autres ne la voient pas.", es: "Veo belleza donde otras quiz\u00e1 no la notan." }, reverse: false },
  { id: 'O2_r55', key: 'O2', en: "Do not like poetry.", text: { fr: "Je n\u2019aime pas la po\u00e9sie.", es: "No me gusta la poes\u00eda." }, reverse: true },
  { id: 'O2_r56', key: 'O2', en: "Do not enjoy going to art museums.", text: { fr: "Je n\u2019aime pas aller aux mus\u00e9es d\u2019art.", es: "No disfruto yendo a museos de arte." }, reverse: true },
  { id: 'O3_p57', key: 'O3', en: "Experience my emotions intensely.", text: { fr: "Je vis mes \u00e9motions intens\u00e9ment.", es: "Vivo mis emociones con intensidad." }, reverse: false },
  { id: 'O3_p58', key: 'O3', en: "Feel others' emotions.", text: { fr: "Je ressens les \u00e9motions des autres.", es: "Siento las emociones de los dem\u00e1s." }, reverse: false },
  { id: 'O3_r59', key: 'O3', en: "Rarely notice my emotional reactions.", text: { fr: "Je remarque rarement mes r\u00e9actions \u00e9motionnelles.", es: "Rara vez noto mis reacciones emocionales." }, reverse: true },
  { id: 'O3_r60', key: 'O3', en: "Don't understand people who get emotional.", text: { fr: "Je ne comprends pas les gens qui s\u2019\u00e9motionnent.", es: "No entiendo a la gente que se emociona." }, reverse: true },
  { id: 'O4_p61', key: 'O4', en: "Prefer variety to routine.", text: { fr: "Je pr\u00e9f\u00e8re la vari\u00e9t\u00e9 \u00e0 la routine.", es: "Prefiero la variedad a la rutina." }, reverse: false },
  { id: 'O4_r62', key: 'O4', en: "Prefer to stick with things that I know.", text: { fr: "Je pr\u00e9f\u00e8re m\u2019en tenir \u00e0 ce que je connais.", es: "Prefiero quedarme con lo que ya conozco." }, reverse: true },
  { id: 'O4_r63', key: 'O4', en: "Dislike changes.", text: { fr: "Je n\u2019aime pas le changement.", es: "No me gustan los cambios." }, reverse: true },
  { id: 'O4_r64', key: 'O4', en: "Am attached to conventional ways.", text: { fr: "Je suis attach\u00e9e aux fa\u00e7ons conventionnelles.", es: "Estoy apegada a lo convencional." }, reverse: true },
  { id: 'O5_p65', key: 'O5', en: "Love to read challenging material.", text: { fr: "J\u2019aime lire des textes exigeants.", es: "Me gusta leer material exigente." }, reverse: false },
  { id: 'O5_r66', key: 'O5', en: "Avoid philosophical discussions.", text: { fr: "J\u2019\u00e9vite les discussions philosophiques.", es: "Evito las discusiones filos\u00f3ficas." }, reverse: true },
  { id: 'O5_r67', key: 'O5', en: "Have difficulty understanding abstract ideas.", text: { fr: "J\u2019ai du mal \u00e0 comprendre les id\u00e9es abstraites.", es: "Me cuesta entender ideas abstractas." }, reverse: true },
  { id: 'O5_r68', key: 'O5', en: "Am not interested in theoretical discussions.", text: { fr: "Les discussions th\u00e9oriques ne m\u2019int\u00e9ressent pas.", es: "No me interesan las discusiones te\u00f3ricas." }, reverse: true },
  { id: 'O6_p69', key: 'O6', en: "Tend to vote for liberal political candidates.", text: { fr: "J\u2019ai tendance \u00e0 voter pour des candidat\u00b7es progressistes.", es: "Suelo votar por candidatos liberales." }, reverse: false },
  { id: 'O6_p70', key: 'O6', en: "Believe that there is no absolute right and wrong.", text: { fr: "Je crois qu\u2019il n\u2019y a pas de bien et de mal absolus.", es: "Creo que no hay un bien y un mal absolutos." }, reverse: false },
  { id: 'O6_r71', key: 'O6', en: "Tend to vote for conservative political candidates.", text: { fr: "J\u2019ai tendance \u00e0 voter pour des candidat\u00b7es conservateurs.", es: "Suelo votar por candidatos conservadores." }, reverse: true },
  { id: 'O6_r72', key: 'O6', en: "Believe that we should be tough on crime.", text: { fr: "Je crois qu\u2019il faut \u00eatre s\u00e9v\u00e8re face au crime.", es: "Creo que debemos ser duros con el crimen." }, reverse: true },
  { id: 'A1_p73', key: 'A1', en: "Trust others.", text: { fr: "Je fais confiance aux autres.", es: "Conf\u00edo en los dem\u00e1s." }, reverse: false },
  { id: 'A1_p74', key: 'A1', en: "Believe that others have good intentions.", text: { fr: "Je crois que les autres ont de bonnes intentions.", es: "Creo que los dem\u00e1s tienen buenas intenciones." }, reverse: false },
  { id: 'A1_p75', key: 'A1', en: "Trust what people say.", text: { fr: "Je fais confiance \u00e0 ce que disent les gens.", es: "Conf\u00edo en lo que dice la gente." }, reverse: false },
  { id: 'A1_r76', key: 'A1', en: "Distrust people.", text: { fr: "Je me m\u00e9fie des gens.", es: "Desconf\u00edo de la gente." }, reverse: true },
  { id: 'A2_r77', key: 'A2', en: "Use others for my own ends.", text: { fr: "J\u2019utilise les autres pour mes fins.", es: "Uso a los dem\u00e1s para mis fines." }, reverse: true },
  { id: 'A2_r78', key: 'A2', en: "Cheat to get ahead.", text: { fr: "Je triche pour avancer.", es: "Hago trampa para avanzar." }, reverse: true },
  { id: 'A2_r79', key: 'A2', en: "Take advantage of others.", text: { fr: "Je profite des autres.", es: "Me aprovecho de los dem\u00e1s." }, reverse: true },
  { id: 'A2_r80', key: 'A2', en: "Obstruct others' plans.", text: { fr: "Je fais obstacle aux plans des autres.", es: "Obstruyo los planes de los dem\u00e1s." }, reverse: true },
  { id: 'A3_p81', key: 'A3', en: "Am concerned about others.", text: { fr: "Je me soucie des autres.", es: "Me preocupo por los dem\u00e1s." }, reverse: false },
  { id: 'A3_p82', key: 'A3', en: "Love to help others.", text: { fr: "J\u2019adore aider les autres.", es: "Me encanta ayudar a los dem\u00e1s." }, reverse: false },
  { id: 'A3_r83', key: 'A3', en: "Am indifferent to the feelings of others.", text: { fr: "Je suis indiff\u00e9rente aux sentiments des autres.", es: "Soy indiferente a los sentimientos ajenos." }, reverse: true },
  { id: 'A3_r84', key: 'A3', en: "Take no time for others.", text: { fr: "Je ne prends pas de temps pour les autres.", es: "No dedico tiempo a los dem\u00e1s." }, reverse: true },
  { id: 'A4_r85', key: 'A4', en: "Love a good fight.", text: { fr: "J\u2019adore une bonne dispute.", es: "Me encanta una buena pelea." }, reverse: true },
  { id: 'A4_r86', key: 'A4', en: "Yell at people.", text: { fr: "Je crie apr\u00e8s les gens.", es: "Grito a la gente." }, reverse: true },
  { id: 'A4_r87', key: 'A4', en: "Insult people.", text: { fr: "J\u2019insulte les gens.", es: "Insulto a la gente." }, reverse: true },
  { id: 'A4_r88', key: 'A4', en: "Get back at others.", text: { fr: "Je me venge.", es: "Me desquit\u00e9 con los dem\u00e1s." }, reverse: true },
  { id: 'A5_r89', key: 'A5', en: "Believe that I am better than others.", text: { fr: "Je crois que je suis meilleure que les autres.", es: "Creo que soy mejor que los dem\u00e1s." }, reverse: true },
  { id: 'A5_r90', key: 'A5', en: "Think highly of myself.", text: { fr: "J\u2019ai une haute opinion de moi-m\u00eame.", es: "Pienso muy bien de m\u00ed misma." }, reverse: true },
  { id: 'A5_r91', key: 'A5', en: "Have a high opinion of myself.", text: { fr: "J\u2019ai une haute opinion de moi.", es: "Tengo una alta opini\u00f3n de m\u00ed misma." }, reverse: true },
  { id: 'A5_r92', key: 'A5', en: "Boast about my virtues.", text: { fr: "Je me vante de mes qualit\u00e9s.", es: "Presumo de mis virtudes." }, reverse: true },
  { id: 'A6_p93', key: 'A6', en: "Sympathize with the homeless.", text: { fr: "Je compatis avec les sans-abri.", es: "Simpatizo con las personas sin hogar." }, reverse: false },
  { id: 'A6_p94', key: 'A6', en: "Feel sympathy for those who are worse off than myself.", text: { fr: "Je compatis avec ceux qui sont moins bien lotis.", es: "Siento simpat\u00eda por quienes est\u00e1n peor que yo." }, reverse: false },
  { id: 'A6_r95', key: 'A6', en: "Am not interested in other people's problems.", text: { fr: "Je ne m\u2019int\u00e9resse pas aux probl\u00e8mes des autres.", es: "No me interesan los problemas de otras personas." }, reverse: true },
  { id: 'A6_r96', key: 'A6', en: "Try not to think about the needy.", text: { fr: "J\u2019essaie de ne pas penser aux personnes dans le besoin.", es: "Intento no pensar en quienes lo necesitan." }, reverse: true },
  { id: 'C1_p97', key: 'C1', en: "Complete tasks successfully.", text: { fr: "Je m\u00e8ne les t\u00e2ches \u00e0 bien.", es: "Completo las tareas con \u00e9xito." }, reverse: false },
  { id: 'C1_p98', key: 'C1', en: "Excel in what I do.", text: { fr: "J\u2019excelle dans ce que je fais.", es: "Destaco en lo que hago." }, reverse: false },
  { id: 'C1_p99', key: 'C1', en: "Handle tasks smoothly.", text: { fr: "Je m\u00e8ne les t\u00e2ches avec aisance.", es: "Manejo las tareas con soltura." }, reverse: false },
  { id: 'C1_p100', key: 'C1', en: "Know how to get things done.", text: { fr: "Je sais faire avancer les choses.", es: "S\u00e9 c\u00f3mo sacar las cosas adelante." }, reverse: false },
  { id: 'C2_p101', key: 'C2', en: "Like to tidy up.", text: { fr: "J\u2019aime ranger.", es: "Me gusta ordenar." }, reverse: false },
  { id: 'C2_r102', key: 'C2', en: "Often forget to put things back in their proper place.", text: { fr: "J\u2019oublie souvent de remettre les choses \u00e0 leur place.", es: "A menudo olvido poner las cosas en su sitio." }, reverse: true },
  { id: 'C2_r103', key: 'C2', en: "Leave a mess in my room.", text: { fr: "Je laisse le bazar dans ma chambre.", es: "Dejo un desastre en mi habitaci\u00f3n." }, reverse: true },
  { id: 'C2_r104', key: 'C2', en: "Leave my belongings around.", text: { fr: "Je laisse mes affaires tra\u00eener.", es: "Dejo mis cosas tiradas." }, reverse: true },
  { id: 'C3_p105', key: 'C3', en: "Keep my promises.", text: { fr: "Je tiens mes promesses.", es: "Cumplo mis promesas." }, reverse: false },
  { id: 'C3_p106', key: 'C3', en: "Tell the truth.", text: { fr: "Je dis la v\u00e9rit\u00e9.", es: "Digo la verdad." }, reverse: false },
  { id: 'C3_r107', key: 'C3', en: "Break rules.", text: { fr: "Je brise les r\u00e8gles.", es: "Rompo las reglas." }, reverse: true },
  { id: 'C3_r108', key: 'C3', en: "Break my promises.", text: { fr: "Je romps mes promesses.", es: "Rompo mis promesas." }, reverse: true },
  { id: 'C4_p109', key: 'C4', en: "Do more than what's expected of me.", text: { fr: "Je fais plus que ce qu\u2019on attend de moi.", es: "Hago m\u00e1s de lo que se espera de m\u00ed." }, reverse: false },
  { id: 'C4_p110', key: 'C4', en: "Work hard.", text: { fr: "Je travaille dur.", es: "Trabajo duro." }, reverse: false },
  { id: 'C4_r111', key: 'C4', en: "Put little time and effort into my work.", text: { fr: "Je mets peu de temps et d\u2019effort dans mon travail.", es: "Pongo poco tiempo y esfuerzo en mi trabajo." }, reverse: true },
  { id: 'C4_r112', key: 'C4', en: "Do just enough work to get by.", text: { fr: "Je fais juste assez pour m\u2019en sortir.", es: "Hago solo lo necesario para salir del paso." }, reverse: true },
  { id: 'C5_p113', key: 'C5', en: "Am always prepared.", text: { fr: "Je suis toujours pr\u00e9par\u00e9e.", es: "Siempre estoy preparada." }, reverse: false },
  { id: 'C5_p114', key: 'C5', en: "Carry out my plans.", text: { fr: "Je m\u00e8ne mes plans \u00e0 bien.", es: "Llevo a cabo mis planes." }, reverse: false },
  { id: 'C5_r115', key: 'C5', en: "Waste my time.", text: { fr: "Je perds mon temps.", es: "Pierdo el tiempo." }, reverse: true },
  { id: 'C5_r116', key: 'C5', en: "Have difficulty starting tasks.", text: { fr: "J\u2019ai du mal \u00e0 commencer les t\u00e2ches.", es: "Me cuesta empezar las tareas." }, reverse: true },
  { id: 'C6_r117', key: 'C6', en: "Jump into things without thinking.", text: { fr: "Je me lance sans r\u00e9fl\u00e9chir.", es: "Me lanzo a las cosas sin pensar." }, reverse: true },
  { id: 'C6_r118', key: 'C6', en: "Make rash decisions.", text: { fr: "Je prends des d\u00e9cisions pr\u00e9cipit\u00e9es.", es: "Tomo decisiones precipitadas." }, reverse: true },
  { id: 'C6_r119', key: 'C6', en: "Rush into things.", text: { fr: "Je me pr\u00e9cipite.", es: "Me precipito." }, reverse: true },
  { id: 'C6_r120', key: 'C6', en: "Act without thinking.", text: { fr: "J\u2019agis sans r\u00e9fl\u00e9chir.", es: "Act\u00fao sin pensar." }, reverse: true },
];

// count check: 120

/** Domaines OCEAN dérivés des facettes (N → ES inversé). */
export const FACET_DOMAIN: Record<string, 'N' | 'E' | 'O' | 'A' | 'C'> = {
  N1: 'N', N2: 'N', N3: 'N', N4: 'N', N5: 'N', N6: 'N',
  E1: 'E', E2: 'E', E3: 'E', E4: 'E', E5: 'E', E6: 'E',
  O1: 'O', O2: 'O', O3: 'O', O4: 'O', O5: 'O', O6: 'O',
  A1: 'A', A2: 'A', A3: 'A', A4: 'A', A5: 'A', A6: 'A',
  C1: 'C', C2: 'C', C3: 'C', C4: 'C', C5: 'C', C6: 'C',
};

/** Somme domaine 24–120 → échelle IPIP-50 10–50 (pour banque traits). */
export function domain120ToTrait50(sum24to120: number): number {
  const clamped = Math.max(24, Math.min(120, sum24to120));
  return Math.round(10 + ((clamped - 24) / 96) * 40);
}

export const BIG_FIVE_120_TEST: SelfTestDefinition = {
  slug: 'big-five',
  version: 'ipip-neo-120-v1',
  format: 'ipip-120',
  source: 'IPIP-NEO-120 (Johnson, 2014)',
  sourceUrl: 'https://ipip.ori.org/30FacetNEO-PI-RItems.htm',
  title: {
    fr: 'Big Five approfondi (IPIP-NEO-120)',
    es: 'Big Five en profundidad (IPIP-NEO-120)',
  },
  description: {
    fr: '120 questions officielles — 5 traits + 30 sous-facettes. ~20 min. Analyse détaillée pour membres.',
    es: '120 preguntas oficiales — 5 rasgos + 30 subfacetas. ~20 min. Análisis detallado para socias.',
  },
  durationMin: 20,
  items: IPIP120_ITEMS,
  scoreKeys: ['E', 'A', 'C', 'ES', 'O'],
  facetKeys: [...IPIP120_FACET_IDS],
  likertMax: 5,
  likertLabels: {
    fr: [
      'Très inexact',
      'Modérément inexact',
      'Ni exact ni inexact',
      'Modérément exact',
      'Très exact',
    ],
    es: [
      'Muy inexacto',
      'Moderadamente inexacto',
      'Ni exacto ni inexacto',
      'Moderadamente exacto',
      'Muy exacto',
    ],
  },
};
