// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/blog" | "/admin/blog/articles/[articleId]/stats" | "/admin/blog/calendar" | "/admin/blog/newsletter" | "/admin/blog/stats" | "/admin/blog/validation" | "/admin/clients" | "/admin/clients/[id]" | "/admin/courses" | "/admin/courses/[courseId]/attendance" | "/admin/promos" | "/admin/vimeo" | "/blog" | "/blog/[slug]" | "/compte" | "/compte/profil" | "/connexion" | "/live/[courseId]" | "/login"
type AppRouteHandlerRoutes = "/api/admin/avatar" | "/api/admin/blog/article-stats/[articleId]" | "/api/admin/blog/articles/[articleId]" | "/api/admin/blog/articles/[articleId]/translate" | "/api/admin/blog/cron/publish-scheduled" | "/api/admin/blog/heatmap/[articleId]" | "/api/admin/blog/newsletter" | "/api/admin/blog/stats" | "/api/admin/blog/validation" | "/api/admin/blog/validation/[validationId]" | "/api/admin/standalone-videos/[id]" | "/api/admin/standalone-videos/pending-count" | "/api/admin/vimeo/[id]/remove" | "/api/admin/vimeo/[id]/schedule" | "/api/admin/vimeo/[id]/validate" | "/api/admin/vimeo/cron/publish-scheduled" | "/api/admin/vimeo/sync-all" | "/api/billing/portal" | "/api/calendar/events" | "/api/calendar/export-ical" | "/api/calendar/feed.ics" | "/api/calendar/mobile-sync" | "/api/checkout" | "/api/client/blog/articles" | "/api/client/blog/articles/[slug]" | "/api/client/blog/articles/id/[articleId]/rate" | "/api/client/blog/articles/id/[articleId]/ratings" | "/api/client/blog/articles/id/[articleId]/scroll-event" | "/api/client/blog/articles/id/[articleId]/view" | "/api/client/newsletter/subscribe" | "/api/client/user/preferences" | "/api/courses/[id]/access" | "/api/courses/list" | "/api/demo-mode/disable" | "/api/demo-mode/enable" | "/api/jitsi/token" | "/api/video/process-recording" | "/api/webhooks/stripe" | "/api/webhooks/vimeo" | "/auth/callback" | "/auth/signout"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/blog" | "/compte"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/blog": {}
  "/admin/blog/articles/[articleId]/stats": { "articleId": string; }
  "/admin/blog/calendar": {}
  "/admin/blog/newsletter": {}
  "/admin/blog/stats": {}
  "/admin/blog/validation": {}
  "/admin/clients": {}
  "/admin/clients/[id]": { "id": string; }
  "/admin/courses": {}
  "/admin/courses/[courseId]/attendance": { "courseId": string; }
  "/admin/promos": {}
  "/admin/vimeo": {}
  "/api/admin/avatar": {}
  "/api/admin/blog/article-stats/[articleId]": { "articleId": string; }
  "/api/admin/blog/articles/[articleId]": { "articleId": string; }
  "/api/admin/blog/articles/[articleId]/translate": { "articleId": string; }
  "/api/admin/blog/cron/publish-scheduled": {}
  "/api/admin/blog/heatmap/[articleId]": { "articleId": string; }
  "/api/admin/blog/newsletter": {}
  "/api/admin/blog/stats": {}
  "/api/admin/blog/validation": {}
  "/api/admin/blog/validation/[validationId]": { "validationId": string; }
  "/api/admin/standalone-videos/[id]": { "id": string; }
  "/api/admin/standalone-videos/pending-count": {}
  "/api/admin/vimeo/[id]/remove": { "id": string; }
  "/api/admin/vimeo/[id]/schedule": { "id": string; }
  "/api/admin/vimeo/[id]/validate": { "id": string; }
  "/api/admin/vimeo/cron/publish-scheduled": {}
  "/api/admin/vimeo/sync-all": {}
  "/api/billing/portal": {}
  "/api/calendar/events": {}
  "/api/calendar/export-ical": {}
  "/api/calendar/feed.ics": {}
  "/api/calendar/mobile-sync": {}
  "/api/checkout": {}
  "/api/client/blog/articles": {}
  "/api/client/blog/articles/[slug]": { "slug": string; }
  "/api/client/blog/articles/id/[articleId]/rate": { "articleId": string; }
  "/api/client/blog/articles/id/[articleId]/ratings": { "articleId": string; }
  "/api/client/blog/articles/id/[articleId]/scroll-event": { "articleId": string; }
  "/api/client/blog/articles/id/[articleId]/view": { "articleId": string; }
  "/api/client/newsletter/subscribe": {}
  "/api/client/user/preferences": {}
  "/api/courses/[id]/access": { "id": string; }
  "/api/courses/list": {}
  "/api/demo-mode/disable": {}
  "/api/demo-mode/enable": {}
  "/api/jitsi/token": {}
  "/api/video/process-recording": {}
  "/api/webhooks/stripe": {}
  "/api/webhooks/vimeo": {}
  "/auth/callback": {}
  "/auth/signout": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/compte": {}
  "/compte/profil": {}
  "/connexion": {}
  "/live/[courseId]": { "courseId": string; }
  "/login": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/blog": never
  "/compte": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
