// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/blog/articles/[articleId]/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/articles/[articleId]/stats">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/articles/[articleId]/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/newsletter">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/stats">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/validation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/validation">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/validation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/boutique/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/boutique">> = Specific
  const handler = {} as typeof import("../../src/app/admin/boutique/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients">> = Specific
  const handler = {} as typeof import("../../src/app/admin/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/courses/[courseId]/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/courses/[courseId]/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/admin/courses/[courseId]/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/courses">> = Specific
  const handler = {} as typeof import("../../src/app/admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/promos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/promos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/promos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/vimeo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vimeo">> = Specific
  const handler = {} as typeof import("../../src/app/admin/vimeo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/boutique/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/boutique">> = Specific
  const handler = {} as typeof import("../../src/app/boutique/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte/blog">> = Specific
  const handler = {} as typeof import("../../src/app/compte/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/boutique/commandes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte/boutique/commandes">> = Specific
  const handler = {} as typeof import("../../src/app/compte/boutique/commandes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/boutique/en-cours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte/boutique/en-cours">> = Specific
  const handler = {} as typeof import("../../src/app/compte/boutique/en-cours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/boutique/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte/boutique">> = Specific
  const handler = {} as typeof import("../../src/app/compte/boutique/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte">> = Specific
  const handler = {} as typeof import("../../src/app/compte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte/planning">> = Specific
  const handler = {} as typeof import("../../src/app/compte/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte/profil">> = Specific
  const handler = {} as typeof import("../../src/app/compte/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/progression/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte/progression">> = Specific
  const handler = {} as typeof import("../../src/app/compte/progression/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/replays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte/replays">> = Specific
  const handler = {} as typeof import("../../src/app/compte/replays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/connexion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connexion">> = Specific
  const handler = {} as typeof import("../../src/app/connexion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/live/[courseId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[courseId]">> = Specific
  const handler = {} as typeof import("../../src/app/live/[courseId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/avatar">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/article-stats/[articleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/article-stats/[articleId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/article-stats/[articleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/articles/[articleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/articles/[articleId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/articles/[articleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/articles/[articleId]/translate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/articles/[articleId]/translate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/articles/[articleId]/translate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/cron/prepare-monthly-validation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/cron/prepare-monthly-validation">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/cron/prepare-monthly-validation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/cron/publish-scheduled/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/cron/publish-scheduled">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/cron/publish-scheduled/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/heatmap/[articleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/heatmap/[articleId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/heatmap/[articleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/newsletter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/newsletter">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/newsletter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/validation/[validationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/validation/[validationId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/validation/[validationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/validation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/validation">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/validation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/printful/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/printful/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/printful/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/printful/product-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/printful/product-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/printful/product-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/standalone-videos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/standalone-videos/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/standalone-videos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/standalone-videos/pending-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/standalone-videos/pending-count">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/standalone-videos/pending-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vimeo/[id]/remove/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vimeo/[id]/remove">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vimeo/[id]/remove/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vimeo/[id]/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vimeo/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vimeo/[id]/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vimeo/[id]/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vimeo/[id]/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vimeo/[id]/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vimeo/cron/publish-scheduled/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vimeo/cron/publish-scheduled">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vimeo/cron/publish-scheduled/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vimeo/sync-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vimeo/sync-all">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vimeo/sync-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/export-ical/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/export-ical">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/export-ical/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/feed.ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/feed.ics">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/feed.ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/mobile-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/mobile-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/mobile-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/blog/articles/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/blog/articles/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/blog/articles/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/blog/articles/id/[articleId]/rate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/blog/articles/id/[articleId]/rate">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/blog/articles/id/[articleId]/rate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/blog/articles/id/[articleId]/ratings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/blog/articles/id/[articleId]/ratings">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/blog/articles/id/[articleId]/ratings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/blog/articles/id/[articleId]/scroll-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/blog/articles/id/[articleId]/scroll-event">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/blog/articles/id/[articleId]/scroll-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/blog/articles/id/[articleId]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/blog/articles/id/[articleId]/view">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/blog/articles/id/[articleId]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/blog/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/blog/articles">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/blog/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/blog/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/blog/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/blog/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/newsletter/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/newsletter/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/newsletter/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/newsletter/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/newsletter/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/newsletter/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/replays/standalone-favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/replays/standalone-favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/replays/standalone-favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client/user/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client/user/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/client/user/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/courses/[id]/access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses/[id]/access">> = Specific
  const handler = {} as typeof import("../../src/app/api/courses/[id]/access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/courses/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/courses/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/demo-mode/disable/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo-mode/disable">> = Specific
  const handler = {} as typeof import("../../src/app/api/demo-mode/disable/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/demo-mode/enable/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo-mode/enable">> = Specific
  const handler = {} as typeof import("../../src/app/api/demo-mode/enable/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jitsi/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jitsi/token">> = Specific
  const handler = {} as typeof import("../../src/app/api/jitsi/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/printful/orders/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/printful/orders/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/printful/orders/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/printful/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/printful/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/printful/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/printful/products/[productId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/printful/products/[productId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/printful/products/[productId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/video/process-recording/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/video/process-recording">> = Specific
  const handler = {} as typeof import("../../src/app/api/video/process-recording/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/vimeo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/vimeo">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/vimeo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/signout">> = Specific
  const handler = {} as typeof import("../../src/app/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compte/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/compte">> = Specific
  const handler = {} as typeof import("../../src/app/compte/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
